services:
  mcp-server:
    build: ./mcp-server
    container_name: mcp-stocks-server
    ports:
      - "3000:3000"
    environment:
      - ALPHAVANTAGE_API_KEY=${ALPHAVANTAGE_API_KEY}
      - PORT=3000
    restart: unless-stopped
    networks:
      - agent-network

  agent:
    build: ./agent
    container_name: stock-agent
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
    depends_on:
      - mcp-server
    restart: unless-stopped
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge